/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

/**
 *
 * @author Administrator
 */
public class phat extends javax.swing.JInternalFrame {

    /**
     * Creates new form phat
     */
    public phat() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        btnsearch = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtemail1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtdg4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txttc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txttc1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtemail2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(52, 143, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm độc giả"));
        jPanel1.setLayout(null);

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N
        btnsearch.setText("Tìm");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch);
        btnsearch.setBounds(260, 50, 80, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 50, 240, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã phiếu mượn");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 30, 120, 17);

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(10, 10, 360, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin độc giả"));
        jPanel4.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Họ tên");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 60, 100, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mã độc giả");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 30, 100, 17);

        txtemail1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemail1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtemail1);
        txtemail1.setBounds(10, 130, 240, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Số điện thoại");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 110, 100, 17);

        txtname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtname1);
        txtname1.setBounds(10, 80, 240, 30);

        txtdg4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdg4ActionPerformed(evt);
            }
        });
        jPanel4.add(txtdg4);
        txtdg4.setBounds(110, 30, 140, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Tiền cọc");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(10, 160, 70, 20);

        txttc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttcActionPerformed(evt);
            }
        });
        jPanel4.add(txttc);
        txttc.setBounds(10, 180, 240, 30);

        kGradientPanel1.add(jPanel4);
        jPanel4.setBounds(10, 120, 360, 230);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Đầu sách", "SL", "Giá sách", "Ngày mượn", "Thời hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowVerticalLines(false);
        jScrollPane3.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(390, 10, 480, 340);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel3.setLayout(null);

        txttc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttc1ActionPerformed(evt);
            }
        });
        jPanel3.add(txttc1);
        txttc1.setBounds(10, 90, 240, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Số ngày quá hạn");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 20, 130, 17);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Tiền phạt");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(10, 70, 70, 20);

        txtemail2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemail2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail2);
        txtemail2.setBounds(10, 40, 240, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        jButton1.setText("Phạt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(260, 50, 133, 57);

        kGradientPanel1.add(jPanel3);
        jPanel3.setBounds(10, 360, 400, 140);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music-and-multimedia.png"))); // NOI18N
        kGradientPanel1.add(jButton2);
        jButton2.setBounds(580, 360, 70, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next (1).png"))); // NOI18N
        kGradientPanel1.add(jButton3);
        jButton3.setBounds(680, 360, 70, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail1ActionPerformed

    private void txtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1ActionPerformed

    private void txtdg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdg4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdg4ActionPerformed

    private void txttcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttcActionPerformed

    private void txttc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttc1ActionPerformed

    private void txtemail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemail2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtdg4;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtemail2;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txttc;
    private javax.swing.JTextField txttc1;
    // End of variables declaration//GEN-END:variables
}
