/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

/**
 *
 * @author Administrator
 */
public class them_the_doc extends javax.swing.JInternalFrame {

    /**
     * Creates new form them_the_doc
     */
    public them_the_doc() {
        initComponents();
        selectMoney();
    }

    void selectMoney(){
        String select = (String) cbodate.getSelectedItem();
        if (select == "1 tháng(Mặc định)") {
            txtmoney.setText("60000");
        }else if (select == "3 tháng") {
            txtmoney.setText("1500000");
        }else if (select == "6 tháng") {
            txtmoney.setText("300000");
        }else if (select == "1 năm") {
            txtmoney.setText("600000");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cbodate = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtmoney = new javax.swing.JTextField();
        btnadd1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(52, 143, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo thẻ mượn"));
        jPanel2.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Thời hạn");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(30, 20, 90, 17);

        cbodate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbodate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 tháng(Mặc định)", "3 tháng", "6 tháng", "1 năm" }));
        cbodate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodateActionPerformed(evt);
            }
        });
        jPanel2.add(cbodate);
        cbodate.setBounds(30, 40, 180, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("VND");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(150, 90, 60, 30);

        txtmoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmoneyActionPerformed(evt);
            }
        });
        jPanel2.add(txtmoney);
        txtmoney.setBounds(30, 90, 110, 30);

        btnadd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnadd1.setText("Thêm");
        jPanel2.add(btnadd1);
        btnadd1.setBounds(30, 130, 140, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Phí thẻ");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(30, 70, 90, 17);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(370, 20, 360, 190);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin độc giả"));
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Họ tên");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 20, 90, 17);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10);
        jTextField10.setBounds(30, 40, 240, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Ngày sinh");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 70, 90, 17);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11);
        jTextField11.setBounds(30, 90, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Địa chỉ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 220, 90, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 240, 90);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField12);
        jTextField12.setBounds(30, 190, 240, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Email");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 170, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 120, 100, 17);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(30, 140, 240, 30);

        kGradientPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 340, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void cbodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodateActionPerformed
        // TODO add your handling code here:
        selectMoney();
    }//GEN-LAST:event_cbodateActionPerformed

    private void txtmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmoneyActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd1;
    private javax.swing.JComboBox<String> cbodate;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtmoney;
    // End of variables declaration//GEN-END:variables
}
