/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import Helper.MessageDialog;
import Helper.Validation;
import controller.UserDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.User;

/**
 *
 * @author Administrator
 */
public class tra_cuu_nv extends javax.swing.JInternalFrame {

    /**
     * Creates new form tra_cuu_nv
     */
    String[] columns = {"USER_ID", "USERNAME", "NAME", "BIRTH_DAY", "GENDER", "PHONE", "EMAIL", "ADDRESS"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);
    UserDAO dao = new UserDAO();
    List<Object[]> list = new ArrayList<>();
    List<Object[]> lstPhone = new ArrayList<>();

    public tra_cuu_nv() {
        initComponents();
        btnupdate.setEnabled(false);
        btnupdate1.setEnabled(false);
        readForm();
    }

    private void readForm() {
        this.list = dao.selectBySQL();
        model.setRowCount(0);
        for (Object[] objects : this.list) {
            this.model.addRow(objects);
        }
        tbluser.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsearch1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(52, 143, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Tra cứu")));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");

        btnsearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N
        btnsearch1.setText("Tìm");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnsearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsearch)
                    .addComponent(btnsearch1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
        );

        kGradientPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 370, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel1.setLayout(null);

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnadd.setText("Thêm nhân viên");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd);
        btnadd.setBounds(40, 40, 180, 50);

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disabled.png"))); // NOI18N
        btnupdate.setText("Vô hiệu hóa");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(40, 160, 180, 50);

        btnupdate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnupdate1.setText("Cập nhật");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate1);
        btnupdate1.setBounds(40, 100, 180, 50);

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(10, 160, 370, 240);

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbluser);

        kGradientPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(390, 10, 452, 402);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed

        DefaultTableModel table = (DefaultTableModel) tbluser.getModel();
        String search = txtsearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbluser.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        if (txtsearch.getText().equals("")) {
            MessageDialog.showMessageDialog(txtsearch, "Mời nhập SĐT cần tìm", "Lỗi");
        }
        
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        them_nv ttd = new them_nv();

        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(ttd);
        ttd.show();
        this.dispose();

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int index = tbluser.getSelectedRow();
        TableModel model = tbluser.getModel();
        String user_id = model.getValueAt(index, 0).toString();
        String id = user_id;
        User us = new User();
        us.setUserID(id);
        if (dao.disableUser(us)) {
            MessageDialog.showMessageDialog(this, "Vô hiệu hóa nhân viên thành công!!! ", "Thông báo");
            readForm();
        }else{
            MessageDialog.showMessageDialog(this, "Vô hiếu hóa nhân viên thât bại", "Lỗi");
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
        // TODO add your handling code here:
        cap_nhat_nv cn = new cap_nhat_nv();
        JDesktopPane desktopPane = getDesktopPane();
        desktopPane.add(cn);
        cn.show();
        this.dispose();
        int index = tbluser.getSelectedRow();
        TableModel model = tbluser.getModel();
        String user_id = model.getValueAt(index, 0).toString();
        String username = model.getValueAt(index, 1).toString();
        String name = model.getValueAt(index, 2).toString();
        String birtDay = model.getValueAt(index, 3).toString();
        String gender = model.getValueAt(index, 4).toString();
        String phone = model.getValueAt(index, 5).toString();
        String email = model.getValueAt(index, 6).toString();
        String address = model.getValueAt(index, 7).toString();

        cn.pack();
        cn.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        cn.txtid.setText(user_id);
        cn.txtuser.setText(username);
        cn.txtname.setText(name);
        cn.txtdate.setText(birtDay);
        String sex = gender;
        if (gender.equalsIgnoreCase("Nam")) {
            cn.rdomale.setSelected(true);
        }
        if (gender.equalsIgnoreCase("Nữ")) {
            cn.rdofemale.setSelected(true);
        }

        cn.txtphone.setText(phone);
        cn.txtemail.setText(email);
        cn.txtaddress.setText(address);

    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void tbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseClicked
        // TODO add your handling code here:
        btnupdate.setEnabled(true);
        btnupdate1.setEnabled(true);
    }//GEN-LAST:event_tbluserMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) tbluser.getModel();
        String search = txtsearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        tbluser.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnupdate1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
