/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Helper.MessageDialog;
import Helper.RoleHelper;
import Helper.Validation;
import controller.UserDAO;
import view.admin.MDI_admin;
import javax.swing.JOptionPane;
import model.User;
import view.employee.MDI_employees;

/**
 *
 * @author Administrator
 */
public class doi_mk extends javax.swing.JInternalFrame {

    /**
     * Creates new form doi_mk
     */
    public doi_mk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtchangepass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(52, 143, 80));
        kGradientPanel1.setkStartColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setLayout(null);

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtname);
        txtname.setBounds(328, 81, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_1logo1.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(30, 80, 266, 147);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(328, 61, 90, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(328, 131, 90, 17);

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(txtpass);
        txtpass.setBounds(328, 151, 240, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login (1).png"))); // NOI18N
        jButton2.setText("Đổi mật khẩu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2);
        jButton2.setBounds(328, 245, 170, 41);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shut-down-button.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1);
        jButton1.setBounds(520, 245, 130, 40);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ĐỔI MẬT KHẨU");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 10, 160, 30);

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 688, 55);

        txtchangepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kGradientPanel1.add(txtchangepass);
        txtchangepass.setBounds(328, 208, 240, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Confirm password");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(328, 188, 142, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if (!(new String(txtchangepass.getPassword()).equals(new String(txtpass.getPassword())))) {
            MessageDialog.showMessageDialog(this, "password không khớp", "Lỗi");
        }
        
        StringBuilder sb = new StringBuilder();
        Validation.ValidateEmpty(txtname, sb, "Vui lòng nhập username");
        Validation.ValidateEmpty(txtpass, sb, "Vui lòng nhập password");
        Validation.ValidateEmpty(txtpass, sb, "Vui lòng nhập password mới");
        if (sb.length()>0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }
        try {
            User us = new User();
            
            us.setPassword(new String(txtchangepass.getPassword()));
            us.setUserName(txtname.getText());
            UserDAO dao = new UserDAO();
            if (dao.update(us)) {
                MessageDialog.showMessageDialog(this, "Đổi mật khẩu thành công", "Thông báo");
                System.exit(0);
                login login = new login();
                login.setVisible(true);
            } else {
                MessageDialog.showMessageDialog(this, "Đổi mật khẩu thất bại", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ques = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không ? ");
        if (ques == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtchangepass;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
